name: Build Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # 手動実行も可能にする
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci
      
      - name: Install Puppeteer dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgbm-dev \
            libx11-6 \
            libx11-xcb1 \
            libxcomposite1 \
            libxcursor1 \
            libxdamage1 \
            libxi-dev \
            libxtst-dev \
            libnss3 \
            libcups2 \
            libxss1 \
            libxrandr2 \
            libasound2 \
            libatk1.0-0 \
            libatk-bridge2.0-0 \
            libpangocairo-1.0-0 \
            libgtk-3-0
      
      - name: Check build script execution
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
          NPX_FLAGS: "--no-sandbox --disable-setuid-sandbox"
        run: |
          # Google Chromeをインストール - 新しい方法でリポジトリを追加
          wget -q -O /tmp/chrome-signing-key.pub https://dl-ssl.google.com/linux/linux_signing_key.pub
          sudo install -D -o root -g root -m 644 /tmp/chrome-signing-key.pub /etc/apt/keyrings/google-chrome.pub
          sudo sh -c 'echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/google-chrome.pub] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list'
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          
          # Chromeの場所を確認
          CHROME_PATH=$(which google-chrome-stable)
          echo "Chrome path: $CHROME_PATH"
          export PUPPETEER_EXECUTABLE_PATH=$CHROME_PATH
          
          # GitHub ActionsのUbuntuではBSD版のsedではなくGNU版のsedが使われるため、-i ""の代わりに-iを使用する
          sed -i 's/sed -i "" /sed -i /g' build.sh
          
          # md-to-pdfにPuppeteer関連のフラグを追加
          sed -i 's/npx md-to-pdf/npx md-to-pdf --puppeteer-args="--no-sandbox --disable-setuid-sandbox"/g' build.sh
          
          # 実行権限を付与
          chmod +x build.sh
          
          # スクリプトを実行
          ./build.sh

      - name: Verify PDF files were created
        run: |
          if [ -f "./履歴書_大野拓.pdf" ] && [ -f "./職務経歴書_大野拓.pdf" ]; then
            echo "✅ PDFファイルの生成に成功しました"
          else
            echo "❌ PDFファイルの生成に失敗しました"
            exit 1
          fi

      - name: Upload PDF files as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pdf-files
          path: |
            ./履歴書_大野拓.pdf
            ./職務経歴書_大野拓.pdf
